In [144]:
import numpy
arr=numpy.array ([10,20,30,40,50])
print (arr)


[10 20 30 40 50]


In [145]:
import numpy as np 
arr1 = np.array ((10,20,30,40,50))
print(arr1)

[10 20 30 40 50]


In [146]:
arr2= np.array ([[1,2,3],[4,5,6]])
print (arr2)  


[[1 2 3]
 [4 5 6]]


In [147]:
arr3= np.array ([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [148]:
#printing the dimension of array
print("Dimension of array: ", arr2.ndim)
#print the shape of array
print("Shape of array: ", arr2.shape)
# print the size of array
print("Size of array: ", arr2.size)



Dimension of array:  2
Shape of array:  (2, 3)
Size of array:  6


In [149]:
#printing the dimension of array
print("Dimension of array: ", arr3.ndim)
#print the shape of array
print("Shape of array: ", arr3.shape)
# print the size of array
print("Size of array: ", arr3.size)



Dimension of array:  3
Shape of array:  (2, 2, 3)
Size of array:  12


In [150]:
#creating a array from list with type float
a=np.array ([[1,2,4],[5,8,7]],dtype='float')
print("Array created using passed list:\n",a)            

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]


In [151]:
#created arrat from tuple
b=np.array ((1,3,2))
print("\n Array created using passed tuple:\n",b)



 Array created using passed tuple:
 [1 3 2]


In [152]:
#create a 3x4 matrix with all zeros 
c=np.zeros((3,4)) 
print("\n An 3x4 matrix with all zeros is: \n", c)



 An 3x4 matrix with all zeros is: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [153]:
#create a constant value array of complex type 
d=np.full((3,3),6,dtype='complex')
print("\n An array initialised with all 6s.","Array type is complex=\n",d)



 An array initialised with all 6s. Array type is complex=
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [154]:
#create an array with random values
import numpy as np
e=np.random.random((2,2)) 
print("\nA random array:\n",e)



A random array:
 [[0.10171014 0.43367706]
 [0.30472549 0.93291917]]


In [155]:
#for x in range (0,31,5)
#create a sequence of integer
#from 0 to 30 with step of 5
f=np.arange (0,31,5)
print("\nA sequential array with steps of 5 :\n",f)



A sequential array with steps of 5 :
 [ 0  5 10 15 20 25 30]


In [156]:
#create a sequence of 11 values in range of 0 to 5
g=np.linspace(0,5,11)
print("\nA Sequential array with 11 values between o and 5 :\n",g)



A Sequential array with 11 values between o and 5 :
 [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [157]:
#reshaping 3x3 array into 2x2x3 array
arr=np.array ([[1,2,3,4],
              [5,2,4,2],
              [1,2,0,1]])
newarr=arr.reshape(2,2,3)
print("\n Orignal array:\n",arr)
print("\n Reshaped array:\n",newarr)



 Orignal array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

 Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [158]:
#Flatten array 
arr=np.array ([[1,2,3],[4,5,6]])
flarr=arr.flatten()
print("\n Original array:\n",arr)
print("\n Flatened array:\n",flarr)
print(arr.ndim)
print(flarr.ndim)



 Original array:
 [[1 2 3]
 [4 5 6]]

 Flatened array:
 [1 2 3 4 5 6]
2
1


In [159]:
#creating array of random sample and then computing it
print("Creating array of given shape and populate it with","random samples from a uniform distribution over (0,1)")
array=np.random.rand(2,3)
print(array)
arr5=np.random.rand(5)
print(arr5)



Creating array of given shape and populate it with random samples from a uniform distribution over (0,1)
[[0.25719573 0.03807883 0.89841986]
 [0.76597871 0.19402111 0.55760747]]
[0.42731759 0.04374377 0.984857   0.16326143 0.97200615]


In [160]:
#Generate 5 different integer number between 15 30
x=np.random.randint(15,30,5)
print(x)


[16 20 24 28 17]


In [161]:
#np.matrix returns a matrix from anarray like object
y=np.matrix (np.arange(12).reshape((3,4)))
print(y)
z=np.matrix([[5,6,7],[4,6,9]])
print (z)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[5 6 7]
 [4 6 9]]


In [162]:
#python programme to demonstrate 
#binary operations in numpy
a=np.array ([[1,2],
             [3,4]])
b=np.array ([[4,3],
             [2,1]])

#add array
print("Array sum:\n",a+b)
#multiplication of array(element wise)
print("Array multiplication:\n",a*b)
#matrix multiplication
print("Matrix multiplication:\n",a.dot(b))


Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]
